### ISSUE TITLE
does it have support for FMOD dsp Plugins?

### ISSUE THREAD

**Issue by sanslash332** [gnFur/ChaiFoxes.FMOD#1]
So, the question on the title :)

Can you add to the library and easily use plugins for FMOD?

Specificically how hard is implement with the lib spatial audio, using plugins like oculus spatialicer, steam audio or resonance audio by google.

A few days ago, I got to use the regular FMOD headers for c# with resonance audio in a small monogame test project, but of course bot are separated libs, and aren't integrated one into the other, like your pluging does, incorporing fmod with the content pipeline of monogame and other awesome stuff.

So... can you do that in the current state of the lib? :P

thanks!

**Comment by Martenfur** [comment]
If I'll ever need them -- I will implement that into the library. But for now -- it is what it is. 
My main priority is making a game, so spreading my time on the thing I may not even need is no good for me. 

And, you know, the native library loading code is all here for you, so you could try doing that yourself. ; - )
