### ISSUE TITLE
MAUI - Android FMOD Studio - Loads Banks but doesn't play anything

### ISSUE THREAD

**Issue by Todd442** [gnFur/ChaiFoxes.FMOD#10]
I know this might be a bit of a stretch but _I've your library FMODForFoxes to work with MAUI using the FMOD Core services and things work fine_ (Nice library). But when I attempt to use the FMOD studio capabilities, all the RC codes indicate things worked but I never get any audio.

I've essentially implemented the same code in MAUI as the reference included in your samples.

     `FMODManager.Init(new AndroidNativeLibrary(), FMODMode.CoreAndStudio, "content");
        List<Bank> _banks = new List<Bank>();
        _banks.Add(await StudioSystem.LoadBank("Master.bank"));
        _banks.Add(await StudioSystem.LoadBank("Master.strings.bank"));
        _banks.Add(await StudioSystem.LoadBank("Vehicles.bank"));

          var _engineDescription = StudioSystem.GetEvent("event:/Vehicles/Car Engine");
        
   
        FMOD.Studio.Util.parseID("{0c8363b4-23af-4f9c-af4b-0951bfd37d84}", out var sfxGuid);
        _engineDescription.LoadSampleData();

         _engineInstance = _engineDescription.CreateInstance();

        //// If you have any parameters set within FMOD Studio, you can change them within the code.
        _engineInstance.SetParameterValue("RPM", 1000);
        _engineInstance.SetParameterValue("Load", -1f);
        _engineInstance.Volume = 1;
        if (_engineInstance.PlaybackState == FMOD.Studio.PLAYBACK_STATE.PLAYING)
        {

            _engineInstance.Stop();
        }
        else
        {

            _engineInstance.Start();
        }`
        
Any idea's what might be happening?

**Comment by Martenfur** [comment]
Yea sorry, I don't support maui, this library is primarily for monogame. Maybe something to do with native libraries not workign correctly. If it's a UWP app it needs its own integration and its own native librarties.
