### ISSUE TITLE
Setting 3D audio attributes doesn't work.

### ISSUE THREAD

**Issue by xThuby** [gnFur/ChaiFoxes.FMOD#13]
Trying to implement 3D audio into my project. I've created a listener and I'm setting its position every frame.
```cs
var position = GameManager.Instance.Player.Position.ToVector3();
listener.Position3D = position;
```
And I'm setting the 3D position of EventInstances when they play.

```cs
var attr = new Attributes3D()
{
    Position = srcPosition.ToVector3(),
};
i.Attributes = attr;
```
If I log to the console the value of either of these attribute positions, it reveals that they're still set to 0, 0, 0. Not sure why it's not updating but it seems like a bug.

**Comment by Martenfur** [comment]
Fixed.
