### ISSUE TITLE
UWP support?

### ISSUE THREAD

**Issue by yesseruser** [gnFur/ChaiFoxes.FMOD#14]
Hi, I was wondering, is UWP support for FmodForFoxes planned/in the works?

**Comment by yyr57695** [comment]
Right on the main project page, the author writes that he's not interested in supporting the UWP platform (or Mac, for that matter) but invites folks to add support themselves.

The writing is pretty clearly on the wall for UWP; it's still supported but no longer under active development, and Microsoft is recommending newer alternatives for both Xbox and Windows development.  Personally, I would recommend that you consider other avenues if possible.
