### ISSUE TITLE
Monogame.DestktopGL.Core Compatiblilty

### ISSUE THREAD

**Issue by monsieurmax** [gnFur/ChaiFoxes.FMOD#2]
Hello gnFur,

Thanks for this great helper library.

I'm currently working with the **DesktopGL.Core** version of Monogame, using .netcore ( hence the name ! )
As this is not relying anymore on the Mono logic to load native library, your library does not manage to load fmod native libraries, using the nuget packages and the instructions you provided.

Any idea on how to make it work ?
I'm far out my comfort zone when it comes to native library loading.
Maybe this lib could help : https://github.com/mellinoe/nativelibraryloader

Thanks in advance for your answer.

**Comment by Martenfur** [comment]
Talked about that in PM. The thing mostly works on Core, I'll look into that when official Core support will be added to Monogame.
