### ISSUE TITLE
Setting root FMOD directory doesn't support parent directories. 

### ISSUE THREAD

**Issue by LordAuric** [gnFur/ChaiFoxes.FMOD#6]
When I attempt to set the main directory on AudioMgr.Init(), it appears to ignore relative parent paths, such as ".."

So when attempting to set the parent folder above where the exe is stored to be the main path it fails:
AudioMgr.Init(".."). It also appears to not support specific paths, like "C:\My Projects\Content".

Any insight on how to work through this would be appreciated!

**Comment by Martenfur** [comment]
It seems root path is passer to monogame's TitleContainer class. Look up how it works, maybe that'll give you some more info. But I dunno, why would you want to use an absolute path or a parent directory of your game as a root?

**Comment by Martenfur** [comment]
Gonna close this one, since there is nothing I can do about it, and it seems like a weird usecase. :V
