### ISSUE TITLE
Suggestion: Add FMODManager.Update to readme

### ISSUE THREAD

**Issue by Indieveloper** [gnFur/ChaiFoxes.FMOD#8]
I never really post or comment stuff on github, so this might not be how an issue should be posted exactly. So apologies in advance, but I had a silly problem that can easily be prevented for future users I think.

I followed the whole setup guide and got it working perfectly, but after some testing of my game I realized the sound stopped working eventually. It took me quite a while to realize that I didn't use
`FMODManager.Update();`
Which I think is responsible for clearing used channels that became free? (And probably more important stuff)
It wasn't mentioned in the readme, and I'm the kind of person to not dive into the demo's haha. (I noticed it in a demo I checked after I was out of ideas)

I know this repo hasn't been updated in a while, but it seems so powerful to me that I think a lot of people use it, and maybe just adding that extra pretty important explanation can help some idiots like me save a few hours haha

Thanks for making my game make sound <3

For extra info: I'm now using MonoGame 3.8 and works perfectly!

EDIT:
I found out how to propose a change, and submitted it. Hope it's useful!

**Comment by Martenfur** [comment]
*And just as you think you've made the guide idiot-proof...*

Updated the readme, and as a bonus migrated the entire thing to support latest monogame, latest fmod and NET6. Might want to check it out.
